### ISSUE TITLE
Can it run on cuda 11.6 or lower torch version?

### ISSUE THREAD

**Issue by wra187611** [5k5000/CLdetection2023#1]
I tried to complie this code, but I am a non-root user on my college's server, so I can't upgrade the cuda version. Since when I tried to install "mmcv>=2.0" encountered the problem:

 RuntimeError:
      The detected CUDA version (11.6) mismatches the version that was used to compile
      PyTorch (12.1). Please make sure to use the same CUDA versions.

So I wonder if I can run this code on cuda 11.6 or lower torch version?

look forward to your reply!

Thanks!

**Comment by LiangYong1216** [comment]
yes, i use torch1.7  python 3.7+cudatoolkit11.0.221 mmpose1.0.0 mmcv2.0.0rc4 and others, it can be run successfuly!!!

**Comment by 5k5000** [comment]
Thanks @LiangYong1216, thanks for your interest.
